### PR TITLE
Fix "space after comma", "columns counts" issues

### LINKED ISSUE #4: Localization: specific string
`en_US.csv` a string example:
```
"Please remove invalid characters: {0}.", "Please remove invalid characters: {0}."
```
provides with the issue:
```
Generating new i18n for en_US.csv at /tmp/translatotron/generated/en_US.json
/tmp/translatotron/node_modules/csv-parse/lib/sync.js:21
  if(err1 !== undefined) throw err1
                         ^

CsvError: Invalid Opening Quote: a quote is found inside a field at line 103
    at Parser.__parse (/tmp/translatotron/node_modules/csv-parse/lib/index.js:619:19)
    at module.exports (/tmp/translatotron/node_modules/csv-parse/lib/sync.js:20:23)
    at /tmp/translatotron/src/index.js:78:29
    at Array.forEach (<anonymous>)
    at /tmp/translatotron/src/index.js:63:9
    at FSReqCallback.oncomplete (fs.js:171:23) {
  code: 'INVALID_OPENING_QUOTE',
  column: 'value',
  empty_lines: 0,
  error: undefined,
  header: false,
  index: 1,
  invalid_field_length: 0,
  quoting: false,
  lines: 103,
  records: 102,
  field: ' '
}

```

```
node src/index.js
```
```
node --version
v14.15.4
```

Thank you for a quick fix

### PR DESCRIPTION
**Pull request by coresh**
Closes #4

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -25,6 +25,9 @@ console.log(`Reading ${legacyFilePath}.`);
 const legacyTranslations = {};
 parse(fs.readFileSync(legacyFilePath, "utf8"), {
   columns: ["key", "value"],
+    relax_column_count: true,
```
Comment (sirugh) [inline src/index.js:28]: I see you added this to solve an issue where column counts may not be identical. Will this cause the output to work as expected? I wish I had added tests for this code 😆

**Comment by sirugh** [comment]
Ok I verified this locally :) Thanks for the fix!
